config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #get 'email/index'
  #root "email#index"
  #resources :books, only: [:create, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "emails#index"

  resources :emails, only: [:create, :show, :destroy, :update]

  resources :tasks, except: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def create
  @book = Book.create(book_params)
  
  respond_to do |format|
      format.html { redirect_to books_path }
      format.js { }
    end
end

private

def book_params
  params.permit(:title, :author)
end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  #GET/EMAILS
  def index
        @emails = Email.all
  end

  #POST/PUT EMAILS
  def create
    @emails = Email.create(object: Faker::Book.title, body: Faker::Lorem.paragraph,read: false)
    respond_to do |format|
      format.js { }
    end
  end

  def show
    @email.update(read: true) if !@email.read

    respond_to do |format|
      format.html{}
      format.js{}
    end
  end

  #PATCH/PUT EMAILS
  def update
    @email = Email.find(params[:id])
    if @email.read == false 
      @email.read = true
      @email.save
    else
      @email.read = false
      @email.save
    end
    respond_to do |format|
      format.js {  }
      format.html{ redirect_to root_path }
    end
  end

  #DELETE EMAILS
  def destroy

    @email = Email.find(params[:id])
    @email.destroy

    respond_to do |format|
      format.js {  }
      format.html{ redirect_to root_path }
    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :authenticate_user!
  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category

    respond_to do |format|
      if @task.save
        format.html do
          flash[:notice] = "Task created"
          redirect_to root_path
        end
        format.js{}
      else
        format.html do
          flash[:notice] = "Please try again"
          redirect_to root_path
        end
      end
    end
    
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all

  end

  def update
    @task = Task.find(params[:id])
    if params[:status] != nil
      if params[:statvalue] == "1"
        @task.status = true
        @task.save
      else
        @task.status = false
        @task.save
      end
    end
    respond_to do |format|
      format.html do
        @task.update(task_params)
        redirect_to tasks_path
        flash[:notice] = "Task edited"
      end
      format.js {}
    end
    
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js{}
    end
  end


  private

  def task_params
    params.permit(:title, :deadline, :description)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/books/_book.html.erb
<li>"<%= book.title %>" by <b><%= book.author  %></b></li>

app/views/books/create.js.erb
alert("le fichier JS est exécuté!");

document.getElementById("book-list").insertAdjacentHTML("beforeend", "<%= j render 'book', book: @book %>")

app/views/books/index.html.erb
 <h1>My To Do List : Books</h1>
<ul id="book-list">
  <% @books.each do |book| %>
    <li>"<%= book.title %>" by <b><%= book.author  %></b></li>
  <% end %>
</ul>

<div class="form">
  <%= form_tag(books_path, method: :post, class: "form", remote: true) do %>
    <label for="title">Title
    <%= text_field_tag  :title %>

    <label for="author">author
    <%= text_field_tag  :author %>

    <%= submit_tag 'create', :name => 'commit'%>
  <% end %>
</div>

app/views/home/index.html.erb
<!--Home#index-->
<h1 class="text-center mb-4">Welcome to my To Do List App !</h1>
<%= render 'layouts/task_form'  %>
<div class="container">
  <ul>
  <% @categories.each do  |category|%>
  <li><%= category.title  %></li>
  <div class="card">
    <ul id="<%=category.title.split.join%>">
      <% category.tasks.each do |task|  %>
      <%if task.status == true%>
        <li id="<%=task.id%>" class = "text-barre">
      <%else%>
        <li id="<%=task.id%>" >
      <%end%>
      
         <%= check_box_tag :statvalue, 1, task.status , data: { remote: true, url: "/tasks/#{task.id}", params: { id: task.id, status: task.status }.to_param, method: "put" }%>
        <%= task.title  %>
        <% unless task.deadline.nil? %>
          , to read: <%= task.deadline.strftime('%D')  %> 
        <% end %>
        <a href="/tasks/<%=task.id%>" data-method="delete" class="fa fa-trash-o" data-remote="true" data-confirm="mandona"></a>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  </ul>
</div>

<div class="container">
  <div class="row">
    <% @tasks.each do |task|  %>
      <div class="card col-3">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "rounded-circle" %>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Gmail-like en AJAX", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mail index", emails_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Mail index", emails_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
    </ul>
    <img class="rounded-circle dropbtn " id="avatar" height="50px" width="50px" src="https://i.pinimg.com/564x/87/4d/33/874d337a2adbd6ee301157d4dbe6c937.jpg">
    <div class="dropdown-content ml-3">
      <%= link_to "Log in", "#", class: "btn btn-outline-light", :id => 'login', "data-toggle" => "modal", 'data-target' => '#loginModal' %>
      <%= link_to "Sign up", "#", class: "btn btn-light", :id => 'signup', "data-toggle" => "modal", 'data-target' => '#loginModal' %>
    </div>
  </div>
</nav>

app/views/layouts/_task.html.erb
<div class="container">
  <div class="row ml-3">
    <div class="offset-md-3 col-md-6 offset-md-3">
      <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form", remote: true)  do %>
        <div class="form-group">
          <%= label_tag "Task", nil, class: "form-label" %>
          <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
        </div>
        <div class="form-group">
          <%= label_tag "Deadline", nil, class: "form-label" %>
          <%= date_field_tag :deadline, nil, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= label_tag "Category", nil, class: "form-label" %>
          <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
        </div>
        <div class="text-center">
          <%= submit_tag("Create task", class: "btn btn-start-order") %>
        </div>
      <%end%>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewTestAjaxRails</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script type="text/javascript" src="application.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <%= yield %>

  </body>

</html>